apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_INSTALL_PLUGINS
              value: {{ .Values.grafana.plugins | quote }}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
          resources:
            requests:
              cpu: {{ .Values.grafana.resources.requests.cpu }}
              memory: {{ .Values.grafana.resources.requests.memory }}
            limits:
              cpu: {{ .Values.grafana.resources.limits.cpu }}
              memory: {{ .Values.grafana.resources.limits.memory }}
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
