apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      containers:
        - name: zabbix-agent
          image: {{ .Values.zabbixAgent.image }}
          ports:
            - containerPort: 10050
          env:
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbixAgent.serverHost | quote }}
            - name: ZBX_ACTIVE_SERVER
              value: {{ .Values.zabbixAgent.serverHost | quote }}
            - name: ZBX_PASSIVESERVERS
              value: {{ .Values.zabbixAgent.passiveServers | quote }}
            - name: ZBX_STARTAGENTS
              value: {{ .Values.zabbixAgent.startAgents | quote }}
            - name: ZBX_HOSTNAME
              value: zabbix-agent-{{ .Release.Name }}
            - name: ZBX_LISTENPORT
              value: "10050"
            - name: ZBX_LISTENIP
              value: "0.0.0.0"
          volumeMounts:
            - name: zabbix-agent-network-conf
              mountPath: /etc/zabbix/zabbix_agentd_network.conf
              subPath: zabbix_agentd_network.conf
      volumes:
        - name: zabbix-agent-network-conf
          configMap:
            name: zabbix-agent-network-conf
