name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: careful-airfoil-470112-u0
  GKE_CLUSTER: cluster-app-helm
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: meu-deploy
  IMAGE_NAME: meu-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: projects/careful-airfoil-470112-u0/locations/us-central1-c/clusters/cluster-app-helm
        location: us-central1-c
        project_id: careful-airfoil-470112-u0

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./monitoring-chart \
          --set image.repository=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ github.sha }}
